#number, shading, color, shape
st = "striped"#H
so = "solid"
op = "open"

gr = "green"
pu = "purple"
re = "red"

ov = "oval"#P
di = "diamond"#
sq = "squiggly"#

# /Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HgD.svg


Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HgD.svg', number: 1, shading: st, color: gr, shape: di)
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HgP.svg', number: 1, shading: st, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HgS.svg', number: 1, shading: st, color: gr, shape: sq)
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HpD.svg', number: 1, shading: st, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HpP.svg', number: 1, shading: st, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HpS.svg', number: 1, shading: st, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HrD.svg', number: 1, shading: st, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HrP.svg', number: 1, shading: st, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HrS.svg', number: 1, shading: st, color: re, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ogd.svg', number: 1, shading: op, color: gr, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1OgP.svg', number: 1, shading: op, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ogs.svg', number: 1, shading: op, color: gr, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Opd.svg', number: 1, shading: op, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1OpP.svg', number: 1, shading: op, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ops.svg', number: 1, shading: op, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ord.svg', number: 1, shading: op, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1OrP.svg', number: 1, shading: op, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ors.svg', number: 1, shading: op, color: re, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sgd.svg', number: 1, shading: so, color: gr, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sgP.svg', number: 1, shading: so, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sgs.svg', number: 1, shading: so, color: gr, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1spd.svg', number: 1, shading: so, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1spP.svg', number: 1, shading: so, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sps.svg', number: 1, shading: so, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1srd.svg', number: 1, shading: so, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1srP.svg', number: 1, shading: so, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1srs.svg', number: 1, shading: so, color: re, shape: sq) 

Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HgD.svg', number: 2, shading: st, color: gr, shape: di)
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HgP.svg', number: 2, shading: st, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HgS.svg', number: 2, shading: st, color: gr, shape: sq)
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HpD.svg', number: 2, shading: st, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HpP.svg', number: 2, shading: st, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HpS.svg', number: 2, shading: st, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HrD.svg', number: 2, shading: st, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HrP.svg', number: 2, shading: st, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HrS.svg', number: 2, shading: st, color: re, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ogd.svg', number: 2, shading: op, color: gr, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2OgP.svg', number: 2, shading: op, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ogs.svg', number: 2, shading: op, color: gr, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Opd.svg', number: 2, shading: op, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2OpP.svg', number: 2, shading: op, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ops.svg', number: 2, shading: op, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ord.svg', number: 2, shading: op, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2OrP.svg', number: 2, shading: op, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ors.svg', number: 2, shading: op, color: re, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sgd.svg', number: 2, shading: so, color: gr, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sgP.svg', number: 2, shading: so, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sgs.svg', number: 2, shading: so, color: gr, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2spd.svg', number: 2, shading: so, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2spP.svg', number: 2, shading: so, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sps.svg', number: 2, shading: so, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2srd.svg', number: 2, shading: so, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2srP.svg', number: 2, shading: so, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2srs.svg', number: 2, shading: so, color: re, shape: sq) 

Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HgD.svg', number: 3, shading: st, color: gr, shape: di)
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HgP.svg', number: 3, shading: st, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HgS.svg', number: 3, shading: st, color: gr, shape: sq)
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HpD.svg', number: 3, shading: st, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HpP.svg', number: 3, shading: st, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HpS.svg', number: 3, shading: st, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HrD.svg', number: 3, shading: st, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HrP.svg', number: 3, shading: st, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HrS.svg', number: 3, shading: st, color: re, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ogd.svg', number: 3, shading: op, color: gr, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3OgP.svg', number: 3, shading: op, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ogs.svg', number: 3, shading: op, color: gr, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Opd.svg', number: 3, shading: op, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3OpP.svg', number: 3, shading: op, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ops.svg', number: 3, shading: op, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ord.svg', number: 3, shading: op, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3OrP.svg', number: 3, shading: op, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ors.svg', number: 3, shading: op, color: re, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sgd.svg', number: 3, shading: so, color: gr, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sgP.svg', number: 3, shading: so, color: gr, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sgs.svg', number: 3, shading: so, color: gr, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3spd.svg', number: 3, shading: so, color: pu, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3spP.svg', number: 3, shading: so, color: pu, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sps.svg', number: 3, shading: so, color: pu, shape: sq) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3srd.svg', number: 3, shading: so, color: re, shape: di) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3srP.svg', number: 3, shading: so, color: re, shape: ov) 
Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3srs.svg', number: 3, shading: so, color: re, shape: sq)




# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HgD.svg', number: 1, shading: st, color: gr, shape: di)
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HgP.svg', number: 1, shading: st, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HgS.svg', number: 1, shading: st, color: gr, shape: sq)
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HpD.svg', number: 1, shading: st, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HpP.svg', number: 1, shading: st, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HpS.svg', number: 1, shading: st, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HrD.svg', number: 1, shading: st, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HrP.svg', number: 1, shading: st, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1HrS.svg', number: 1, shading: st, color: re, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ogd.svg', number: 1, shading: op, color: gr, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1OgP.svg', number: 1, shading: op, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ogs.svg', number: 1, shading: op, color: gr, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Opd.svg', number: 1, shading: op, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1OpP.svg', number: 1, shading: op, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ops.svg', number: 1, shading: op, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ord.svg', number: 1, shading: op, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1OrP.svg', number: 1, shading: op, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1Ors.svg', number: 1, shading: op, color: re, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sgd.svg', number: 1, shading: so, color: gr, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sgP.svg', number: 1, shading: so, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sgs.svg', number: 1, shading: so, color: gr, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1spd.svg', number: 1, shading: so, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1spP.svg', number: 1, shading: so, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1sps.svg', number: 1, shading: so, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1srd.svg', number: 1, shading: so, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1srP.svg', number: 1, shading: so, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/1srs.svg', number: 1, shading: so, color: re, shape: sq) 

# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HgD.svg', number: 2, shading: st, color: gr, shape: di)
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HgP.svg', number: 2, shading: st, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HgS.svg', number: 2, shading: st, color: gr, shape: sq)
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HpD.svg', number: 2, shading: st, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HpP.svg', number: 2, shading: st, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HpS.svg', number: 2, shading: st, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HrD.svg', number: 2, shading: st, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HrP.svg', number: 2, shading: st, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2HrS.svg', number: 2, shading: st, color: re, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ogd.svg', number: 2, shading: op, color: gr, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2OgP.svg', number: 2, shading: op, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ogs.svg', number: 2, shading: op, color: gr, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Opd.svg', number: 2, shading: op, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2OpP.svg', number: 2, shading: op, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ops.svg', number: 2, shading: op, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ord.svg', number: 2, shading: op, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2OrP.svg', number: 2, shading: op, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2Ors.svg', number: 2, shading: op, color: re, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sgd.svg', number: 2, shading: so, color: gr, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sgP.svg', number: 2, shading: so, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sgs.svg', number: 2, shading: so, color: gr, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2spd.svg', number: 2, shading: so, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2spP.svg', number: 2, shading: so, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2sps.svg', number: 2, shading: so, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2srd.svg', number: 2, shading: so, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2srP.svg', number: 2, shading: so, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/2srs.svg', number: 2, shading: so, color: re, shape: sq) 

# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HgD.svg', number: 3, shading: st, color: gr, shape: di)
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HgP.svg', number: 3, shading: st, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HgS.svg', number: 3, shading: st, color: gr, shape: sq)
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HpD.svg', number: 3, shading: st, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HpP.svg', number: 3, shading: st, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HpS.svg', number: 3, shading: st, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HrD.svg', number: 3, shading: st, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HrP.svg', number: 3, shading: st, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3HrS.svg', number: 3, shading: st, color: re, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ogd.svg', number: 3, shading: op, color: gr, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3OgP.svg', number: 3, shading: op, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ogs.svg', number: 3, shading: op, color: gr, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Opd.svg', number: 3, shading: op, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3OpP.svg', number: 3, shading: op, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ops.svg', number: 3, shading: op, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ord.svg', number: 3, shading: op, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3OrP.svg', number: 3, shading: op, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3Ors.svg', number: 3, shading: op, color: re, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sgd.svg', number: 3, shading: so, color: gr, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sgP.svg', number: 3, shading: so, color: gr, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sgs.svg', number: 3, shading: so, color: gr, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3spd.svg', number: 3, shading: so, color: pu, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3spP.svg', number: 3, shading: so, color: pu, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3sps.svg', number: 3, shading: so, color: pu, shape: sq) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3srd.svg', number: 3, shading: so, color: re, shape: di) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3srP.svg', number: 3, shading: so, color: re, shape: ov) 
# Card.create(img:'/Users/ellyn/Development/Mod3/fewpjs-project-mode-guidelines/tes-backend/app/images/svg/icons/3srs.svg', number: 3, shading: so, color: re, shape: sq)
